import os
from importlib import import_module

from lib.elastic import ElasticClient

elasticClient = ElasticClient()

for entry in os.scandir('src/scraper'):

    # Check if entry is a file (because of autogenerated __pycache__)
    if entry.is_file():
        # Fetch module name
        module_name = os.path.splitext(entry.name)[0]

        # Import class __Scraper__ dynamically, create intance of given class and call the 'run' method
        Scraper = getattr(import_module(f'scraper.{module_name}'), '__Scraper__')
        scraper_instance = Scraper()
        scraper_instance.run()

        import json
        with open('data.json', 'w', encoding='utf-8') as f:
            json.dump(scraper_instance.getData(), f, ensure_ascii=False, indent=4)
        #elasticClient.bulkToIndex(scraper_instance.getData(), 'posts')
