import os
from importlib import import_module

from scripts.data_extraction.lib.elastic import ElasticClient

elasticClient = ElasticClient()

for entry in os.scandir('scraper'):

    # Check if entry is a file (because of autogenerated __pycache__)
    if entry.is_file():
        # Fetch module name
        module_name = os.path.splitext(entry.name)[0]

        # Import class __Scraper__ dynamically, create intance of given class and call the 'run' method
        Scraper = getattr(import_module(f'scraper.{module_name}'), '__Scraper__')
        scraper_instance = Scraper()
        scraper_instance.run()

        elasticClient.bulk_to_index(scraper_instance.getData(), 'posts')
