name: DEPLOY_PRODUCTION

on:
   push:
      branches:
         - master
      paths:
         - app/**
         - '!app/README.md'

jobs:
   deploy:
      runs-on: ubuntu-20.04
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: 14.x

         - name: Restore package cache
           uses: actions/cache@v2
           id: cache
           with:
              path: |
                 ./app/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('./app/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - name: install dependencies
           working-directory: ./app
           if: steps.yarn-cache.outputs.cache-hit != 'true'
           run: yarn --frozen-lockfile --non-interactive

         - name: build Vue app
           working-directory: ./app
           run: yarn build:production

         - name: rsync deployments
           uses: burnett01/rsync-deployments@4.1
           with:
              switches: -avzr --delete
              path: app/dist/
              remote_path: ${{ secrets.DEPLOYMENT_PATH }}
              remote_host: ${{ secrets.DEPLOYMENT_SERVER_PRODUCTION }}
              remote_user: ${{ secrets.DEPLOYMENT_USER }}
              remote_key: ${{ secrets.DEPLOYMENT_KEY }}
