name: CI

on:
   push:
      branches: [staging, master]
   pull_request:
      branches: [staging, master]

jobs:
   build:
      runs-on: ubuntu-20.04
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: 14.x

         - name: install dependencies
           working-directory: ./app
           run: yarn install --pure-lockfile --non-interactive

         - name: build Vue app
           working-directory: ./app
           run: yarn build:production

   lint:
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: 14.x

         - name: install dependencies
           working-directory: ./app
           run: yarn install --pure-lockfile --non-interactive

         - name: lint Vue app
           working-directory: ./app
           run: yarn lint
