name: CI

on:
   pull_request:
      branches: [staging, master]
      paths:
         - app/**
         - '!app/README.md'

jobs:
   build:
      runs-on: ubuntu-20.04
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: 16.x

         - name: Restore package cache
           uses: actions/cache@v2
           id: cache
           with:
              path: |
                 ./app/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('./app/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - name: install dependencies
           working-directory: ./app
           if: steps.yarn-cache.outputs.cache-hit != 'true'
           run: yarn --frozen-lockfile --non-interactive

         - name: build Vue app
           working-directory: ./app
           run: yarn build:production

   lint:
      runs-on: ubuntu-latest
      steps:
         - name: checkout
           uses: actions/checkout@v2

         - name: setup node
           uses: actions/setup-node@v1
           with:
              node-version: 16.x

         - name: Restore package cache
           uses: actions/cache@v2
           id: cache
           with:
              path: |
                 ./app/node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('./app/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-yarn-

         - name: install dependencies
           working-directory: ./app
           if: steps.yarn-cache.outputs.cache-hit != 'true'
           run: yarn --frozen-lockfile --non-interactive

         - name: lint Vue app
           working-directory: ./app
           run: yarn lint
